export const WRITE_ORDER_REPOSITORY = Symbol("WRITE_ORDER_REPOSITORY");
export const READ_ORDER_REPOSITORY = Symbol("READ_ORDER_REPOSITORY");

export const POSTGRES_CONNECTION = Symbol("POSTGRESS_CONNECTION");
export const POSTGRESS_PRISMA_CLIENT = Symbol("POSTGRESS_PRISMA_CLIENT");

export const MONGO_CONNECTION = Symbol("MONGO_CONNECTION");
export const MONGO_COLLECTION = Symbol("MONGO_COLLECTION");

export const REDIS_CONNECTION = Symbol("REDIS_CONNECTION");
export const ORDER_CACHE = Symbol("ORDER_CACHE");

export const KAFKA_CONNECTION = Symbol("KAFKA_CONNECTION");
export const KAFKA_PRODUCER = Symbol("KAFKA_PRODUCER");

export const EVENT_BUS = Symbol("EVENT_BUS");

export const TELEMETRY = Symbol("TELEMETRY");