export const WRITE_ORDER_REPOSITORY = Symbol("WRITE_ORDER_REPOSITORY");
export const READ_ORDER_REPOSITORY = Symbol("READ_ORDER_REPOSITORY");

export const POSTGRES_WRITE_CONNECTION = Symbol("POSTGRES_WRITE_CONNECTION");
export const POSTGRES_WRITE_PRISMA_CLIENT = Symbol("POSTGRES_WRITE_PRISMA_CLIENT");
export const POSTGRES_READ_CONNECTION = Symbol("POSTGRES_READ_CONNECTION");
export const POSTGRES_READ_PRISMA_CLIENT = Symbol("POSTGRES_READ_PRISMA_CLIENT");

export const MONGO_READ_CONNECTION = Symbol("MONGO_READ_CONNECTION");
export const MONGO_READ_COLLECTION = Symbol("MONGO_READ_COLLECTION");
export const MONGO_WRITE_CONNECTION = Symbol("MONGO_WRITE_CONNECTION");
export const MONGO_WRITE_COLLECTION = Symbol("MONGO_WRITE_COLLECTION");

export const REDIS_CONNECTION = Symbol("REDIS_CONNECTION");
export const ORDER_CACHE = Symbol("ORDER_CACHE");

export const KAFKA_CONNECTION = Symbol("KAFKA_CONNECTION");
export const KAFKA_PRODUCER = Symbol("KAFKA_PRODUCER");

export const EVENT_BUS = Symbol("EVENT_BUS");

export const TELEMETRY = Symbol("TELEMETRY");