// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

const postgresUser = env("POSTGRES_USER");
const postgresPassword = env("POSTGRES_PASSWORD");
const postgresHost = env("POSTGRES_HOST");
const postgresPort = env("POSTGRES_PORT");
const payments_db_name = env("PAYMENTS_DB_NAME");

if (!postgresUser || !postgresPassword || !postgresHost || !postgresPort || !payments_db_name) {
  throw new Error("Missing required environment variables for PostgreSQL connection");
}

const url = `postgresql://${postgresUser}:${postgresPassword}@${postgresHost}:${postgresPort}/${payments_db_name}`;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url,
  },
});
